# Generated by Django 5.0.6 on 2024-09-11 23:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='fecha_disponible',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
