# Generated by Django 5.0.6 on 2024-09-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_menu_fecha_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='fecha_disponible',
            field=models.DateField(),
        ),
    ]
