# Generated by Django 5.0.6 on 2024-09-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_menu_fecha_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='fecha_disponible',
            field=models.DateField(null=True),
        ),
    ]
