# Generated by Django 5.0.6 on 2024-09-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_menu_fecha_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='platos',
            field=models.ManyToManyField(blank=True, null=True, to='gestion.plato'),
        ),
    ]
