# Generated by Django 5.1.1 on 2024-09-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_plato_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='platos',
            field=models.ManyToManyField(blank=True, to='gestion.plato'),
        ),
    ]
